language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key: frWZZ0flRmFYzhH8NzlFYfLg48XUlgRfKqB7fSFzpLSpCmw5jY+ptaLrDNWQI8hIuvmtm2KeOFCvMnymRHAk+8YGAp/OCZKl6gg7XYV4nF0U28j2U/VvfBa5mXd6HaN+UOIZ++pOa8oU70AphNP/Pzf8Gmj8nMHAYhwuNsJCGP8=
  app: klusters
